/* Generates src/styles.css from the app's own stylesheets, so the design
   system can never drift from what orkaytiles.com actually ships.
   Re-run it whenever app/globals.css or app/z9/z9.css changes. */
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const app = resolve(here, '../../app');
const pub = resolve(here, '../../public');
const out = resolve(here, '../src');

mkdirSync(`${out}/fonts`, { recursive: true });
for (const f of ['hanken-600.woff2', 'hanken-700.woff2']) {
  copyFileSync(`${pub}/fonts/${f}`, `${out}/fonts/${f}`);
}

const sources = [
  ['globals.css', `${app}/globals.css`],
  ['z9.css', `${app}/z9/z9.css`],
];

const parts = sources.map(([label, path]) => {
  let css = readFileSync(path, 'utf8');
  // fonts ship inside the design system, so their absolute app paths become relative
  css = css.replace(/url\((['"]?)\/fonts\//g, "url($1./fonts/");
  // decorative art lives in the app's public dir and is not part of the system
  css = css.replace(/url\((['"]?)\/img\//g, "url($1./img/");
  return `/* ─── ${label} ─────────────────────────────────────────── */\n${css}`;
});

writeFileSync(
  `${out}/styles.css`,
  `/* GENERATED by scripts/build-css.mjs — edit app/globals.css or app/z9/z9.css instead. */\n\n${parts.join('\n\n')}`,
);
console.log(`styles.css: ${parts.join('').length} bytes from ${sources.length} sources`);
