/* Generator for content/worldmap.ts: world land path + projected export pins
   + arcs from Morbi. Edit MARKETS below, then run from the repo root:
   node scripts/genmap.mjs */
import { writeFileSync } from 'node:fs';
import { geoNaturalEarth1, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';

const topo = await (await fetch('https://unpkg.com/world-atlas@2.0.2/countries-110m.json')).json();
const world = feature(topo, topo.objects.countries);
world.features = world.features.filter((f) => f.id !== '010'); // drop Antarctica

const W = 1000;
const projection = geoNaturalEarth1().fitWidth(W, world);
const path = geoPath(projection);
const [[, y0], [, y1]] = path.bounds(world);
const H = Math.ceil(y1 - y0);
projection.fitExtent([[0, 0], [W, H]], world);

const landPath = world.features.map((f) => path(f)).join('');

const ORIGIN = { name: 'Morbi · India', lon: 70.83, lat: 22.81 };
const MARKETS = [
  { name: 'United Arab Emirates', lon: 55.3, lat: 25.2 },
  { name: 'Saudi Arabia', lon: 46.7, lat: 24.6 },
  { name: 'Qatar', lon: 51.2, lat: 25.3 },
  { name: 'Kuwait', lon: 47.9, lat: 29.3 },
  { name: 'Oman', lon: 57.5, lat: 21.5 },
  { name: 'Iraq', lon: 43.7, lat: 33.2 },
  { name: 'United States', lon: -96.5, lat: 38.5 },
  { name: 'Mexico', lon: -102.5, lat: 23.6 },
  { name: 'Brazil', lon: -51.9, lat: -14.2 },
  { name: 'Chile', lon: -70.9, lat: -35.7 },
  { name: 'United Kingdom', lon: -1.5, lat: 52.5 },
  { name: 'Germany', lon: 10.4, lat: 51.1 },
  { name: 'Italy', lon: 12.5, lat: 42.8 },
  { name: 'Spain', lon: -3.7, lat: 40.4 },
  { name: 'Poland', lon: 19.1, lat: 52.0 },
  { name: 'Russia', lon: 44.0, lat: 55.0 },
  { name: 'South Africa', lon: 25.0, lat: -29.0 },
  { name: 'Kenya', lon: 37.9, lat: 0.2 },
  { name: 'Nigeria', lon: 8.7, lat: 9.1 },
  { name: 'Ghana', lon: -1.2, lat: 7.9 },
  { name: 'Egypt', lon: 29.8, lat: 26.8 },
  { name: 'Australia', lon: 134.4, lat: -25.3 },
  { name: 'Indonesia', lon: 106.8, lat: -6.2 },
  { name: 'Vietnam', lon: 105.8, lat: 21.0 },
  { name: 'Thailand', lon: 100.5, lat: 14.5 },
  { name: 'Philippines', lon: 121.8, lat: 13.5 },
  { name: 'South Korea', lon: 127.8, lat: 36.5 },
  { name: 'Sri Lanka', lon: 80.7, lat: 7.5 },
  { name: 'Nepal', lon: 84.1, lat: 28.4 },
  { name: 'Canada', lon: -106.3, lat: 52.9 },
  { name: 'France', lon: 2.2, lat: 46.2 },
  { name: 'Netherlands', lon: 5.3, lat: 52.1 },
  { name: 'Greece', lon: 21.8, lat: 39.1 },
  { name: 'Romania', lon: 24.9, lat: 45.9 },
  { name: 'Turkey', lon: 35.2, lat: 38.9 },
  { name: 'Jordan', lon: 36.2, lat: 30.6 },
  { name: 'Bahrain', lon: 50.6, lat: 26.0 },
  { name: 'Malaysia', lon: 101.9, lat: 4.2 },
  { name: 'Singapore', lon: 103.8, lat: 1.35 },
  { name: 'Japan', lon: 138.2, lat: 36.2 },
];

const r1 = (n) => Math.round(n * 10) / 10;
const [ox, oy] = projection([ORIGIN.lon, ORIGIN.lat]).map(r1);

const pins = MARKETS.map((m) => {
  const [x, y] = projection([m.lon, m.lat]).map(r1);
  return { name: m.name, x, y };
});

/* quadratic arc lifted perpendicular to the chord, always bowing upward */
const arc = (x, y) => {
  const mx = (ox + x) / 2, my = (oy + y) / 2;
  const dx = x - ox, dy = y - oy;
  const dist = Math.hypot(dx, dy);
  const k = 0.22 * dist;
  let nx = -dy / (dist || 1), ny = dx / (dist || 1);
  if (ny > 0) { nx = -nx; ny = -ny; }
  return `M ${ox} ${oy} Q ${r1(mx + nx * k)} ${r1(my + ny * k)} ${x} ${y}`;
};

const out = `/* GENERATED by scripts/genmap.mjs — Natural Earth projection, ${W}×${H}.
   Land from world-atlas 110m (Antarctica dropped). Pins are export markets;
   arcs run from Morbi to each pin. Regenerate rather than hand-edit. */

export const MAP_W = ${W};
export const MAP_H = ${H};

export const origin = { name: '${ORIGIN.name}', x: ${ox}, y: ${oy} };

export const pins: { name: string; x: number; y: number }[] = ${JSON.stringify(pins, null, 2)};

export const arcs: string[] = ${JSON.stringify(pins.map((p) => arc(p.x, p.y)), null, 2)};

export const landPath = ${JSON.stringify(landPath)};
`;

writeFileSync(new URL('../content/worldmap.ts', import.meta.url), out);
console.log('pins:', pins.length, 'size:', out.length, 'H:', H);
